# Generated by Django 6.0.3 on 2026-04-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("requirements", models.TextField()),
                ("amenities", models.TextField()),
                ("member_count", models.IntegerField(default=0)),
                (
                    "cover_image",
                    models.ImageField(blank=True, upload_to="club_covers/"),
                ),
                ("tags", models.ManyToManyField(to="finalApp.tag")),
            ],
        ),
    ]
