# Generated by Django 6.0.3 on 2026-04-19 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finalApp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("university", models.CharField(max_length=200)),
                (
                    "liked_clubs",
                    models.ManyToManyField(
                        blank=True, related_name="liked_by", to="finalApp.club"
                    ),
                ),
                (
                    "passed_clubs",
                    models.ManyToManyField(
                        blank=True, related_name="passed_by", to="finalApp.club"
                    ),
                ),
                ("tags", models.ManyToManyField(to="finalApp.tag")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
