# Generated by Django 6.0.4 on 2026-05-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalApp', '0002_repair_profile_enrolled_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='club_images/'),
        ),
    ]
