# Generated by Django 6.0.4 on 2026-05-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalApp', '0002_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='club',
            name='emailContact',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='club',
            name='insta',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='club',
            name='tag1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='club',
            name='tag2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='club',
            name='vLink',
            field=models.URLField(blank=True, default=''),
        ),
    ]
