# Generated by Django 6.0.3 on 2026-05-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalApp', '0003_club_category_club_emailcontact_club_insta_club_tag1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='enrolled',
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
