# Generated by Django 6.0.4 on 2026-05-10 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def populate_club_slugs(apps, schema_editor):
    Club = apps.get_model('finalApp', 'Club')

    for club in Club.objects.all():
        if club.slug:
            continue

        base_slug = slugify(club.name) or f"club-{club.pk}"
        slug = base_slug
        counter = 2

        while Club.objects.filter(slug=slug).exclude(pk=club.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1

        club.slug = slug
        club.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('finalApp', '0003_club_category_club_emailcontact_club_insta_club_tag1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=120),
        ),
        migrations.RunPython(populate_club_slugs, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='finalApp.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'club')},
            },
        ),
    ]
