# Generated by Django 6.0.3 on 2026-05-09 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalApp', '0004_remove_profile_enrolled_profile_interests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='insta',
        ),
        migrations.RemoveField(
            model_name='club',
            name='vLink',
        ),
    ]
