# Generated by Django 6.0.3 on 2026-05-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalApp', '0005_remove_club_insta_remove_club_vlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
