# Generated by Django 6.0.3 on 2026-05-10 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalApp', '0004_club_slug_clubmembership'),
        ('finalApp', '0007_alter_profile_interests'),
    ]

    operations = [
    ]
