# Generated by Django 6.0.3 on 2026-05-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalApp', '0008_merge_20260510_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('time', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('hostClub', models.CharField(max_length=100)),
                ('requirements', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
