# Generated by Django 6.0.4 on 2026-05-13 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalApp', '0010_alter_chatmessage_author_alter_chatmessage_club_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventName',
            new_name='name',
        ),
    ]
