# Generated by Django 6.0.4 on 2026-05-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalApp', '0011_alter_event_options_remove_event_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmembership',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
