# Generated by Django 6.0.4 on 2026-05-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalApp', '0011_rename_eventname_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='enrolled',
            field=models.BooleanField(default=True),
        ),
    ]
