# Generated by Django 6.0.4 on 2026-05-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalApp', '0012_club_enrolled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='enrolled',
        ),
        migrations.AddField(
            model_name='profile',
            name='enrolled',
            field=models.BooleanField(default='True'),
        ),
    ]
