# Generated by Django 6.0.4 on 2026-05-14 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalApp', '0013_remove_club_enrolled_profile_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='finalApp.club'),
        ),
    ]
